#!/usr/bin/env python3
"""
Setup script for Senergy Register Scanner

This script helps configure the scanner for your specific setup.
"""

import serial.tools.list_ports
import platform
import os

def detect_serial_ports():
    """Detect available serial ports."""
    ports = []
    
    try:
        # Use pyserial to list ports
        available_ports = serial.tools.list_ports.comports()
        for port in available_ports:
            ports.append({
                'device': port.device,
                'description': port.description,
                'hwid': port.hwid
            })
    except ImportError:
        print("⚠️  pyserial not installed. Install with: pip install pyserial")
        return []
    
    return ports

def get_default_port():
    """Get default port based on operating system."""
    system = platform.system().lower()
    
    if system == "windows":
        return "COM3"  # Common Windows port
    elif system == "linux":
        return "/dev/ttyUSB0"  # Common Linux port
    elif system == "darwin":  # macOS
        return "/dev/tty.usbserial"  # Common macOS port
    else:
        return "/dev/ttyUSB0"  # Default fallback

def check_dependencies():
    """Check if required dependencies are installed."""
    missing_deps = []
    
    try:
        import pymodbus
    except ImportError:
        missing_deps.append("pymodbus")
    
    try:
        import serial
    except ImportError:
        missing_deps.append("pyserial")
    
    return missing_deps

def create_config_file(port, baudrate=9600, slave_id=1):
    """Create a configuration file for the scanner."""
    config_content = f"""# Senergy Register Scanner Configuration
# Generated by setup_scanner.py

# Serial connection settings
PORT = "{port}"
BAUDRATE = {baudrate}
SLAVE_ID = {slave_id}

# Scanning settings
TIMEOUT = 3.0
SCAN_DELAY = 0.1  # Delay between register reads (seconds)

# Output settings
VERBOSE = True
SAVE_TO_FILE = False
OUTPUT_FILE = "register_scan_results.txt"
"""
    
    with open("scanner_config.py", "w") as f:
        f.write(config_content)
    
    print(f"✅ Configuration saved to scanner_config.py")

def main():
    """Main setup function."""
    print("🔧 Senergy Register Scanner Setup")
    print("=" * 40)
    
    # Check dependencies
    print("\n📦 Checking dependencies...")
    missing_deps = check_dependencies()
    
    if missing_deps:
        print("❌ Missing dependencies:")
        for dep in missing_deps:
            print(f"   - {dep}")
        print("\n💡 Install missing dependencies with:")
        print(f"   pip install {' '.join(missing_deps)}")
        return
    else:
        print("✅ All dependencies are installed")
    
    # Detect serial ports
    print("\n🔌 Detecting serial ports...")
    ports = detect_serial_ports()
    
    if ports:
        print("Available serial ports:")
        for i, port in enumerate(ports, 1):
            print(f"  {i}. {port['device']} - {port['description']}")
        
        print(f"\n💡 Recommended port: {get_default_port()}")
        
        # Ask user to select port
        try:
            choice = input(f"\nSelect port (1-{len(ports)}) or press Enter for default ({get_default_port()}): ").strip()
            
            if choice.isdigit() and 1 <= int(choice) <= len(ports):
                selected_port = ports[int(choice) - 1]['device']
            else:
                selected_port = get_default_port()
        except KeyboardInterrupt:
            print("\n⚠️  Setup cancelled")
            return
    else:
        print("⚠️  No serial ports detected")
        selected_port = get_default_port()
        print(f"💡 Using default port: {selected_port}")
    
    # Get other settings
    print(f"\n⚙️  Configuration settings:")
    print(f"   Port: {selected_port}")
    
    try:
        baudrate_input = input("   Baudrate (default 9600): ").strip()
        baudrate = int(baudrate_input) if baudrate_input else 9600
        
        slave_id_input = input("   Slave ID (default 1): ").strip()
        slave_id = int(slave_id_input) if slave_id_input else 1
        
    except ValueError:
        print("⚠️  Invalid input, using defaults")
        baudrate = 9600
        slave_id = 1
    
    # Create configuration
    print(f"\n💾 Creating configuration...")
    create_config_file(selected_port, baudrate, slave_id)
    
    # Create usage instructions
    print(f"\n📋 Usage instructions:")
    print(f"   1. Connect your inverter to {selected_port}")
    print(f"   2. Ensure inverter is powered on")
    print(f"   3. Run the scanner:")
    print(f"      python senergy_register_scanner.py")
    print(f"   4. Or run examples:")
    print(f"      python example_register_scan.py")
    
    print(f"\n✅ Setup complete!")
    print(f"   Configuration: scanner_config.py")
    print(f"   Scanner: senergy_register_scanner.py")
    print(f"   Examples: example_register_scan.py")

if __name__ == "__main__":
    main()
